name: infra
on:
  workflow_dispatch:        # lancio manuale
    inputs:
      apply:
        description: "Esegui provisioning"
        required: true
        default: "yes"

jobs:
  provision:
    if: github.event.inputs.apply == 'yes'
    runs-on: ubuntu-latest
    env:
      HCLOUD_TOKEN: ${{ secrets.HCLOUD_PROVISIONING_KEY_FOR_WORKFLOWS }}
    steps:
      - uses: actions/checkout@v4

      - name: install hcloud CLI
        run: |
          sudo curl -fsSL https://github.com/hetznercloud/cli/releases/latest/download/hcloud-linux-amd64.tar.gz | \
            tar -xz -C /usr/local/bin hcloud
          hcloud version

      - name: ensure ssh key exists (optional)
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_PROVISIONING_KEY_FOR_WORKFLOWS }}
          PUB: ${{ secrets.SSH_DEPLOY_PUB_KEY }}
        run: |
          if [ -n "$PUB" ]; then
            hcloud ssh-key list | grep -q deploy-key || hcloud ssh-key add --name deploy-key --public-key "$PUB"
          fi

      - name: run IaC script
        run: |
          chmod +x infra/deploy_infra.sh
          ./infra/deploy_infra.sh
